//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryPlate.BackendResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryPlate.BackendResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string A_user_with_this_login_already_exists {
            get {
                return ResourceManager.GetString("A_user_with_this_login_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token timespan cannot be null..
        /// </summary>
        public static string Access_token_timespan_cannot_be_null {
            get {
                return ResourceManager.GetString("Access_token_timespan_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token timespan is required..
        /// </summary>
        public static string Access_token_timespan_is_required {
            get {
                return ResourceManager.GetString("Access_token_timespan_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed username characters are required..
        /// </summary>
        public static string Allowed_username_characters_are_required {
            get {
                return ResourceManager.GetString("Allowed_username_characters_are_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string An_unknown_failure_has_occurred {
            get {
                return ResourceManager.GetString("An_unknown_failure_has_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant has been created successfully.
        /// </summary>
        public static string Applicant_has_been_created_successfully {
            get {
                return ResourceManager.GetString("Applicant_has_been_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant has been deleted successfully..
        /// </summary>
        public static string Applicant_has_been_deleted_successfully {
            get {
                return ResourceManager.GetString("Applicant_has_been_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant has been updated successfully..
        /// </summary>
        public static string Applicant_has_been_updated_successfully {
            get {
                return ResourceManager.GetString("Applicant_has_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disable Two-Factor Authentication for user with ID &apos;{0}&apos; as it&apos;s not currently enabled..
        /// </summary>
        public static string Cannot_disable_2FA_for_user_with_Id {
            get {
                return ResourceManager.GetString("Cannot_disable_2FA_for_user_with_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate recovery codes for username &apos;{0}&apos; as they do not have Two-Factor Authentication enabled..
        /// </summary>
        public static string Cannot_generate_recovery_codes {
            get {
                return ResourceManager.GetString("Cannot_generate_recovery_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required..
        /// </summary>
        public static string Code_is_required {
            get {
                return ResourceManager.GetString("Code_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        public static string Confirm_password_is_required {
            get {
                return ResourceManager.GetString("Confirm_password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        public static string Confirm_your_email {
            get {
                return ResourceManager.GetString("Confirm_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation link to change email has been sent. Please check your email..
        /// </summary>
        public static string Confirmation_link_to_change_email_has_been_sent {
            get {
                return ResourceManager.GetString("Confirmation_link_to_change_email_has_been_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is required.
        /// </summary>
        public static string Date_of_Birth_is_required {
            get {
                return ResourceManager.GetString("Date_of_Birth_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of entity &quot;{0}&quot; ({1}) failed. {2}..
        /// </summary>
        public static string Deletion_of_entity_failed {
            get {
                return ResourceManager.GetString("Deletion_of_entity_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Email_is_already_taken {
            get {
                return ResourceManager.GetString("Email_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string Email_is_invalid {
            get {
                return ResourceManager.GetString("Email_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &quot;{0}&quot; with key &quot;{1}&quot; was not found..
        /// </summary>
        public static string Entity_with_key_was_not_found {
            get {
                return ResourceManager.GetString("Entity_with_key_was_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing user name..
        /// </summary>
        public static string Error_changing_user_name {
            get {
                return ResourceManager.GetString("Error_changing_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing your user name..
        /// </summary>
        public static string Error_changing_your_user_name {
            get {
                return ResourceManager.GetString("Error_changing_your_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has not been uploaded..
        /// </summary>
        public static string File_has_not_been_uploaded {
            get {
                return ResourceManager.GetString("File_has_not_been_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty..
        /// </summary>
        public static string File_is_empty {
            get {
                return ResourceManager.GetString("File_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File storage settings have been updated successfully..
        /// </summary>
        public static string File_storage_settings_have_been_updated_successfully {
            get {
                return ResourceManager.GetString("File_storage_settings_have_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string First_name_is_required {
            get {
                return ResourceManager.GetString("First_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height is required..
        /// </summary>
        public static string Height_is_required {
            get {
                return ResourceManager.GetString("Height_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity settings have been updated successfully..
        /// </summary>
        public static string Identity_settings_have_been_updated_successfully {
            get {
                return ResourceManager.GetString("Identity_settings_have_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid applicant ID..
        /// </summary>
        public static string Invalid_applicant_Id {
            get {
                return ResourceManager.GetString("Invalid_applicant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authenticator code entered..
        /// </summary>
        public static string Invalid_authenticator_code_entered {
            get {
                return ResourceManager.GetString("Invalid_authenticator_code_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client request..
        /// </summary>
        public static string Invalid_client_request {
            get {
                return ResourceManager.GetString("Invalid_client_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalid_login_attempt {
            get {
                return ResourceManager.GetString("Invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recovery code entered..
        /// </summary>
        public static string Invalid_recovery_code_entered {
            get {
                return ResourceManager.GetString("Invalid_recovery_code_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report Id..
        /// </summary>
        public static string Invalid_report_Id {
            get {
                return ResourceManager.GetString("Invalid_report_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role ID..
        /// </summary>
        public static string Invalid_role_Id {
            get {
                return ResourceManager.GetString("Invalid_role_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tenant name..
        /// </summary>
        public static string Invalid_tenant_name {
            get {
                return ResourceManager.GetString("Invalid_tenant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string Invalid_token {
            get {
                return ResourceManager.GetString("Invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user ID..
        /// </summary>
        public static string Invalid_user_Id {
            get {
                return ResourceManager.GetString("Invalid_user_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title is required..
        /// </summary>
        public static string Job_title_is_required {
            get {
                return ResourceManager.GetString("Job_title_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string Last_name_is_required {
            get {
                return ResourceManager.GetString("Last_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout is not enabled for this user..
        /// </summary>
        public static string Lockout_is_not_enabled_for_this_user {
            get {
                return ResourceManager.GetString("Lockout_is_not_enabled_for_this_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed number of attachments must not exceed 3..
        /// </summary>
        public static string Maximum_allowed_number_of_attachments_must_not_exceed_3 {
            get {
                return ResourceManager.GetString("Maximum_allowed_number_of_attachments_must_not_exceed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be null..
        /// </summary>
        public static string Method_cannot_be_null {
            get {
                return ResourceManager.GetString("Method_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum allowed number of attachments must be at least 1..
        /// </summary>
        public static string Minimum_allowed_number_of_attachments_must_be_at_least_1 {
            get {
                return ResourceManager.GetString("Minimum_allowed_number_of_attachments_must_be_at_least_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string N_A {
            get {
                return ResourceManager.GetString("N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        public static string New_password_is_required {
            get {
                return ResourceManager.GetString("New_password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be at least 6 characters..
        /// </summary>
        public static string New_password_must_be_at_least_6_characters {
            get {
                return ResourceManager.GetString("New_password_must_be_at_least_6_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must not exceed 200 characters..
        /// </summary>
        public static string New_password_must_not_exceed_200_characters {
            get {
                return ResourceManager.GetString("New_password_must_not_exceed_200_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required..
        /// </summary>
        public static string Old_password_is_required {
            get {
                return ResourceManager.GetString("Old_password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only those between the ages of 18 and 28 are allowed for enlisting..
        /// </summary>
        public static string Only_those_between_the_ages_of_18_and_28_are_allowed_for_enlisting {
            get {
                return ResourceManager.GetString("Only_those_between_the_ages_of_18_and_28_are_allowed_for_enlisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only those who weigh between 50 and 200 with normal BMI are allowed for enlisting..
        /// </summary>
        public static string Only_those_who_weigh_between_50_and_200_with_normal_BMI_are_allowed_for_enlisting {
            get {
                return ResourceManager.GetString("Only_those_who_weigh_between_50_and_200_with_normal_BMI_are_allowed_for_enlisting" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only those whose BMI between 18.5 and 24.9 are allowed for enlisting..
        /// </summary>
        public static string Only_those_whose_BMI_between_18_5_and_24_9_are_allowed_for_enlisting {
            get {
                return ResourceManager.GetString("Only_those_whose_BMI_between_18_5_and_24_9_are_allowed_for_enlisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only those whose heights between 100 and 250 with normal BMI are allowed for enlisting..
        /// </summary>
        public static string Only_those_whose_heights_between_100_and_250_with_normal_BMI_are_allowed_for_enlisting {
            get {
                return ResourceManager.GetString("Only_those_whose_heights_between_100_and_250_with_normal_BMI_are_allowed_for_enli" +
                        "sting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string Optimistic_concurrency_failure {
            get {
                return ResourceManager.GetString("Optimistic_concurrency_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain &apos;password&apos;..
        /// </summary>
        public static string Password_cannot_contain_password {
            get {
                return ResourceManager.GetString("Password_cannot_contain_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain username..
        /// </summary>
        public static string Password_cannot_contain_username {
            get {
                return ResourceManager.GetString("Password_cannot_contain_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Password_is_required {
            get {
                return ResourceManager.GetString("Password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string Password_must_be_at_least_6_characters {
            get {
                return ResourceManager.GetString("Password_must_be_at_least_6_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed 200 characters..
        /// </summary>
        public static string Password_must_not_exceed_200_characters {
            get {
                return ResourceManager.GetString("Password_must_not_exceed_200_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link was sent. Please check your email..
        /// </summary>
        public static string Password_reset_link_was_sent {
            get {
                return ResourceManager.GetString("Password_reset_link_was_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string Passwords_must_be_at_least_length_characters {
            get {
                return ResourceManager.GetString("Passwords_must_be_at_least_length_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_digit {
            get {
                return ResourceManager.GetString("Passwords_must_have_at_least_one_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_lowercase {
            get {
                return ResourceManager.GetString("Passwords_must_have_at_least_one_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string Passwords_must_have_at_least_one_non_alphanumeric_character {
            get {
                return ResourceManager.GetString("Passwords_must_have_at_least_one_non_alphanumeric_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string Passwords_must_have_at_least_one_uppercase {
            get {
                return ResourceManager.GetString("Passwords_must_have_at_least_one_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is_required..
        /// </summary>
        public static string Phone_number_is_required {
            get {
                return ResourceManager.GetString("Phone_number_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string Please_confirm_your_account_by_clicking_here {
            get {
                return ResourceManager.GetString("Please_confirm_your_account_by_clicking_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email..
        /// </summary>
        public static string Please_confirm_your_email {
            get {
                return ResourceManager.GetString("Please_confirm_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string Please_reset_your_password_by_clicking_here {
            get {
                return ResourceManager.GetString("Please_reset_your_password_by_clicking_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the application tenant mode..
        /// </summary>
        public static string Please_specify_the_application_tenant_mode {
            get {
                return ResourceManager.GetString("Please_specify_the_application_tenant_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture is required..
        /// </summary>
        public static string Profile_picture_is_required {
            get {
                return ResourceManager.GetString("Profile_picture_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Code is required..
        /// </summary>
        public static string Recovery_Code_is_required {
            get {
                return ResourceManager.GetString("Recovery_Code_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Code Redemption Failed.
        /// </summary>
        public static string Recovery_Code_Redemption_Failed {
            get {
                return ResourceManager.GetString("Recovery_Code_Redemption_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference name is required..
        /// </summary>
        public static string Reference_name_is_required {
            get {
                return ResourceManager.GetString("Reference_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token timespan cannot be null..
        /// </summary>
        public static string Refresh_token_timespan_cannot_be_null {
            get {
                return ResourceManager.GetString("Refresh_token_timespan_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token timespan is required..
        /// </summary>
        public static string Refresh_token_timespan_is_required {
            get {
                return ResourceManager.GetString("Refresh_token_timespan_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token timespan must be greater than access token expiry time..
        /// </summary>
        public static string Refresh_token_timespan_must_be_greater_than_access_token_expiry_time {
            get {
                return ResourceManager.GetString("Refresh_token_timespan_must_be_greater_than_access_token_expiry_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111111 is not a valid Social security number..
        /// </summary>
        public static string Repeated_Ones_are_not_valid_Social_security_number {
            get {
                return ResourceManager.GetString("Repeated_Ones_are_not_valid_Social_security_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 333333333 is not a valid Social security number..
        /// </summary>
        public static string Repeated_Threes_are_not_valid_Social_security_number {
            get {
                return ResourceManager.GetString("Repeated_Threes_are_not_valid_Social_security_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Reset_your_password {
            get {
                return ResourceManager.GetString("Reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been created successfully..
        /// </summary>
        public static string Role_has_been_created_successfully {
            get {
                return ResourceManager.GetString("Role_has_been_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been deleted successfully..
        /// </summary>
        public static string Role_has_been_deleted_successfully {
            get {
                return ResourceManager.GetString("Role_has_been_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been updated successfully..
        /// </summary>
        public static string Role_has_been_updated_successfully {
            get {
                return ResourceManager.GetString("Role_has_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Role_name_is_already_taken {
            get {
                return ResourceManager.GetString("Role_name_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string Role_name_is_invalid {
            get {
                return ResourceManager.GetString("Role_name_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is required..
        /// </summary>
        public static string Role_name_is_required {
            get {
                return ResourceManager.GetString("Role_name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security number is required.
        /// </summary>
        public static string Social_security_number_is_required {
            get {
                return ResourceManager.GetString("Social_security_number_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security number must contain only 9-digits..
        /// </summary>
        public static string Social_security_number_must_contain_only_9_digits {
            get {
                return ResourceManager.GetString("Social_security_number_must_contain_only_9_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security number must not contain consecutive digits..
        /// </summary>
        public static string Social_security_number_must_not_contain_consecutive_digits {
            get {
                return ResourceManager.GetString("Social_security_number_must_not_contain_consecutive_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname is required..
        /// </summary>
        public static string Surname_is_required {
            get {
                return ResourceManager.GetString("Surname_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant has been created successfully..
        /// </summary>
        public static string Tenant_has_been_created_successfully {
            get {
                return ResourceManager.GetString("Tenant_has_been_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applicant is not found..
        /// </summary>
        public static string The_applicant_is_not_found {
            get {
                return ResourceManager.GetString("The_applicant_is_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string The_password_and_confirmation_password_do_not_match {
            get {
                return ResourceManager.GetString("The_password_and_confirmation_password_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified role is already registered..
        /// </summary>
        public static string The_specified_role_is_already_registered {
            get {
                return ResourceManager.GetString("The_specified_role_is_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified role is already registered in the given tenant..
        /// </summary>
        public static string The_specified_role_is_already_registered_in_the_given_tenant {
            get {
                return ResourceManager.GetString("The_specified_role_is_already_registered_in_the_given_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username and email are already registered..
        /// </summary>
        public static string The_specified_username_and_email_are_already_registered {
            get {
                return ResourceManager.GetString("The_specified_username_and_email_are_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username and email are already registered in the given tenant..
        /// </summary>
        public static string The_specified_username_and_email_are_already_registered_in_the_given_tenant {
            get {
                return ResourceManager.GetString("The_specified_username_and_email_are_already_registered_in_the_given_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token settings have been updated successfully..
        /// </summary>
        public static string Token_settings_have_been_updated_successfully {
            get {
                return ResourceManager.GetString("Token_settings_have_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication code is required..
        /// </summary>
        public static string Two_factor_authentication_code_is_required {
            get {
                return ResourceManager.GetString("Two_factor_authentication_code_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication code must be at least 6 character long..
        /// </summary>
        public static string Two_factor_authentication_code_must_be_at_least_6_character_long {
            get {
                return ResourceManager.GetString("Two_factor_authentication_code_must_be_at_least_6_character_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication code must not exceed 7 characters..
        /// </summary>
        public static string Two_factor_authentication_code_must_not_exceed_7_characters {
            get {
                return ResourceManager.GetString("Two_factor_authentication_code_must_not_exceed_7_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Fa has been disabled. You can reenable Two-Factor Authentication when you setup an authenticator app..
        /// </summary>
        public static string Two_factor_authentication_has_been_disabled {
            get {
                return ResourceManager.GetString("Two_factor_authentication_has_been_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication required..
        /// </summary>
        public static string Two_factor_authentication_required {
            get {
                return ResourceManager.GetString("Two_factor_authentication_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new tenant in single tenant mode..
        /// </summary>
        public static string Unable_to_create_new_tenant_in_single_tenant_mode {
            get {
                return ResourceManager.GetString("Unable_to_create_new_tenant_in_single_tenant_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete static role..
        /// </summary>
        public static string Unable_to_delete_static_role {
            get {
                return ResourceManager.GetString("Unable_to_delete_static_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete static user..
        /// </summary>
        public static string Unable_to_delete_static_user {
            get {
                return ResourceManager.GetString("Unable_to_delete_static_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load applicant..
        /// </summary>
        public static string Unable_to_load_applicant {
            get {
                return ResourceManager.GetString("Unable_to_load_applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load report..
        /// </summary>
        public static string Unable_to_load_report {
            get {
                return ResourceManager.GetString("Unable_to_load_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load role..
        /// </summary>
        public static string Unable_to_load_role {
            get {
                return ResourceManager.GetString("Unable_to_load_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user..
        /// </summary>
        public static string Unable_to_load_user {
            get {
                return ResourceManager.GetString("Unable_to_load_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update static user..
        /// </summary>
        public static string Unable_to_update_static_user {
            get {
                return ResourceManager.GetString("Unable_to_update_static_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred deleting user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Unexpected_error_occurred_deleting_user_with_Id {
            get {
                return ResourceManager.GetString("Unexpected_error_occurred_deleting_user_with_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred disabling Two-Factor Authentication for user with ID &apos;{0}&apos;..
        /// </summary>
        public static string Unexpected_error_occurred_disabling_2FA {
            get {
                return ResourceManager.GetString("Unexpected_error_occurred_disabling_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string User_already_has_a_password_set {
            get {
                return ResourceManager.GetString("User_already_has_a_password_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string User_already_in_role {
            get {
                return ResourceManager.GetString("User_already_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added without files..
        /// </summary>
        public static string User_has_been_added_without_files {
            get {
                return ResourceManager.GetString("User_has_been_added_without_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created successfully..
        /// </summary>
        public static string User_has_been_created_successfully {
            get {
                return ResourceManager.GetString("User_has_been_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted successfully..
        /// </summary>
        public static string User_has_been_deleted_successfully {
            get {
                return ResourceManager.GetString("User_has_been_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated successfully..
        /// </summary>
        public static string User_has_been_updated_successfully {
            get {
                return ResourceManager.GetString("User_has_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated successfully without updating his/her roles as the user is static type..
        /// </summary>
        public static string User_has_been_updated_successfully_without_updating_his_her_roles_as_the_user_is_static_type {
            get {
                return ResourceManager.GetString("User_has_been_updated_successfully_without_updating_his_her_roles_as_the_user_is_" +
                        "static_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required..
        /// </summary>
        public static string User_Id_is_required {
            get {
                return ResourceManager.GetString("User_Id_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permissions have been updated successfully..
        /// </summary>
        public static string User_permissions_have_been_updated_successfully {
            get {
                return ResourceManager.GetString("User_permissions_have_been_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID &apos;{0}&apos; has been deleted..
        /// </summary>
        public static string User_with_Id_deleted {
            get {
                return ResourceManager.GetString("User_with_Id_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID &apos;{0}&apos; logged in with Two-Factor Authentication..
        /// </summary>
        public static string User_with_Id_UserId_logged_in_with_2Fa {
            get {
                return ResourceManager.GetString("User_with_Id_UserId_logged_in_with_2Fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has been confirmed successfully..
        /// </summary>
        public static string Username_has_been_confirmed_successfully {
            get {
                return ResourceManager.GetString("Username_has_been_confirmed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Username_is_already_taken {
            get {
                return ResourceManager.GetString("Username_is_already_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string Username_is_invalid {
            get {
                return ResourceManager.GetString("Username_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string Username_is_required {
            get {
                return ResourceManager.GetString("Username_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 6 characters..
        /// </summary>
        public static string Username_must_be_at_least_6_characters {
            get {
                return ResourceManager.GetString("Username_must_be_at_least_6_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must not exceed 200 characters..
        /// </summary>
        public static string Username_must_not_exceed_200_characters {
            get {
                return ResourceManager.GetString("Username_must_not_exceed_200_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null.
        /// </summary>
        public static string value_cannot_be_null {
            get {
                return ResourceManager.GetString("value_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid..
        /// </summary>
        public static string Verification_code_is_invalid {
            get {
                return ResourceManager.GetString("Verification_code_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email has been sent. Please check your email..
        /// </summary>
        public static string Verification_email_has_been_sent {
            get {
                return ResourceManager.GetString("Verification_email_has_been_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is required..
        /// </summary>
        public static string Weight_is_required {
            get {
                return ResourceManager.GetString("Weight_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are forbidden to access {0}..
        /// </summary>
        public static string You_are_forbidden {
            get {
                return ResourceManager.GetString("You_are_forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re locked out..
        /// </summary>
        public static string You_are_locked_out {
            get {
                return ResourceManager.GetString("You_are_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access {0}..
        /// </summary>
        public static string You_are_not_authorized {
            get {
                return ResourceManager.GetString("You_are_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated new recovery codes..
        /// </summary>
        public static string You_have_generated_new_recovery_codes {
            get {
                return ResourceManager.GetString("You_have_generated_new_recovery_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully created a new account..
        /// </summary>
        public static string You_have_successfully_created_a_new_account {
            get {
                return ResourceManager.GetString("You_have_successfully_created_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is deactivated. Please contact your administrator..
        /// </summary>
        public static string Your_account_is_deactivated_Please_contact_your_administrator {
            get {
                return ResourceManager.GetString("Your_account_is_deactivated_Please_contact_your_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app has been verified..
        /// </summary>
        public static string Your_authenticator_app_has_been_verified {
            get {
                return ResourceManager.GetString("Your_authenticator_app_has_been_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app key has been reset, you will need to configure your authenticator app using the new key..
        /// </summary>
        public static string Your_authenticator_app_key_has_been_reset {
            get {
                return ResourceManager.GetString("Your_authenticator_app_key_has_been_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been changed successfully..
        /// </summary>
        public static string Your_email_has_been_changed_successfully {
            get {
                return ResourceManager.GetString("Your_email_has_been_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been successfully changed..
        /// </summary>
        public static string Your_email_has_been_successfully_changed {
            get {
                return ResourceManager.GetString("Your_email_has_been_successfully_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is unchanged..
        /// </summary>
        public static string Your_email_is_unchanged {
            get {
                return ResourceManager.GetString("Your_email_is_unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Your_password_has_been_changed {
            get {
                return ResourceManager.GetString("Your_password_has_been_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string Your_password_has_been_reset {
            get {
                return ResourceManager.GetString("Your_password_has_been_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Your_password_has_been_set {
            get {
                return ResourceManager.GetString("Your_password_has_been_set", resourceCulture);
            }
        }
    }
}
